# This is the yaml configuration for Christian's Web Server
# Please remember YAML files use tab indentation and NOT spaces.
server-version: "1.0"
debug: false
bind-address: "0.0.0.0"
port: 80
index-page: "index.html"
persistence:
  use-persistent-connections: false   # Whether or not to maintain persistent TCP connections with clients
  persistent-connection-timeout: 6000 # TCP connection timeout length in milliseconds -> Default: 6000
files:
  web-root: "./html"
logging:
  enabled: true
  http-log-file-path: "./logs"
  http-log-file-name: "http_log"
  http-log-file-max-length: 300    # Max http log file length in lines -> Default: 300
  error-log-file-path: "./logs"
  error-log-file-name: "error_log"
  error-log-file-max-length: 300   # Max error log file length in lines -> Default: 300
  error-log-minlevel: WARN         # Options: DEBUG, VERBOSE, INFO, WARN (default), SEVERE, FATAL